version: "3.4"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
    - 27017:27017
    command: --smallfiles
  invent:
    image: my12345/dsti-invent
    container_name: "invent"
    ports:
    - 8081:8081
    expose:
    - 8081
    depends_on:
    - mongodb
